apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http-porte
    port: 80
    protocol: TCP
    targetPort: {{.Values.deploy.containerPortName}}
  selector:
{{ include  "labels" . | indent 5 }}
  type: {{.Values.service.type }}
