apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: weboo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: docker.io/hadilotfy/iti-webapp:build-${BUILD_NUM}
        name: website-image
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http-port
          protocol: TCP

